---
title: "Bivariate Viz"
---

Use this file to generate a professional looking **bivariate** visualization.  The visualization will not perfect the first time but you are expected to improve it throughout the semester especially after covering advanced topics such as effective viz.

```{r}
#| eval: true
library(ggplot2)
# Import data
elections <- read.csv("https://mac-stat.github.io/data/election_2020_county.csv")
```



```{r}

ggplot(elections, aes(y = repub_pct_20, x = median_age)) +
  geom_point(color = "light blue" ) + 
  geom_smooth()+
  labs(x = "Median Age (year)", y = "The 2020 Republican Country-level Support", title = "Relationship between Median Age and 2020 Republican Election Suppport", caption = "Made by Shaylee")

fig.alt = "Scatter Plot showing the Relationship between Median Age (x-axis) and 2020 Republican Election Suppport (y-axis). Use a line of best fit to show a possible weak positive relationship where most of the data is clustered between age 30-50 and 25-75% support."

```

